## Reporte Práctica 2 Primera Parte

# EJEMPLO MÉTODO GRADIENTE CONJUGADO

Para este método, utilizaremos el dataset de Breast Cancer Wisconsin para 


### Gradiente Conjugado

El método del gradiente conjugado por su siglas en íngles CGM, es metodo iterativo para resolver sistemas de ecuaciones lineales.


$$Ax = b$$


Donde Anxn is una matriz definida pooitiva. Este problema es equivalente al problema de minimización:

$$min\phi(x) = \frac{1}{2}x^{T}Ax-b^{T}x$$

El gradiente de $\phi$ es igual al residual del sistema lineal,

$$\nabla\phi(x) = Ax -b := r(x)$$

En particular en $x = x_{k}$, tenemos:

$$r_{k} = Ax_{k} - b$$




In [37]:
import Opt_HC_CG as opt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [50]:
dataset_bcw = np.loadtxt("../datasets/breast_cancer_wisconsin_(original)_dataset.txt", delimiter = ',')

In [110]:
target_bcw = dataset_bcw[:,0]
data_bcw = dataset_bcw[ : , 1:29]
std_transform = StandardScaler()
dat_bcw_sca = std_transform.fit_transform(data_bcw)
betas = np.ones([dat_bcw_sca.shape[0]+1,dat_bcw_sca.shape[1]])
betas = betas

In [111]:
def yhat(beta0,beta,x):
    
    y = 1/(1+np.exp(-(beta0+beta@x.T)))    
    return y

In [136]:
beta0 = np.array([1/29])
beta = (np.ones(dat_bcw_sca.shape[1]).T)*1/29
P = np.diag((yhat(beta0,beta,dat_bcw_sca)*(1-yhat(beta0,beta,dat_bcw_sca))))

In [137]:
hessiana = 2*dat_bcw_sca.T@P@dat_bcw_sca

In [138]:
fo = -2*dat_bcw_sca.T@(yhat(beta0,beta,dat_bcw_sca)-target_bcw)

In [139]:
v=np.ones(28)
optime = opt.cgm(hessiana, fo, v)

In [140]:
inversed = std_transform.inverse_transform(optime)

In [141]:
inversed

array([-1.65450530e+00,  1.90110048e+01,  1.72802949e+02,  9.60416713e+02,
        9.51395224e-02,  4.71338005e-02,  1.37950413e-01,  6.00628539e-02,
        1.82634007e-01,  6.48256596e-02,  5.34576133e-01,  1.17068317e+00,
        2.15958316e+00,  4.52154265e+01,  7.51073251e-03,  2.60530402e-02,
        1.09561033e-02,  1.32488873e-02,  2.16111319e-02,  3.42759042e-03,
        3.56110210e+01,  2.73184923e+01,  1.06772720e+02, -8.14023931e+02,
        1.34253236e-01,  3.06292004e-01,  3.50235091e-01,  1.15574358e-01])

In [142]:
np.linalg.solve(hessiana, fo)

array([-4.41223326e+00, -5.67162220e-02,  3.28335126e+00,  8.52704649e-01,
       -1.03480456e-01, -1.10081558e+00,  5.99993765e-01,  2.69912797e-01,
        3.70845536e-02,  2.62236726e-01,  4.59845153e-01, -8.49686519e-02,
       -3.44278439e-01,  9.92390661e-02,  1.47957563e-01,  1.64034173e-02,
       -6.88797261e-01,  2.16181769e-01,  1.27616455e-01, -1.55815844e-01,
        3.99449197e+00,  2.86412102e-01, -7.50736561e-03, -2.94567031e+00,
        7.67747698e-02,  3.22444373e-01,  3.61534595e-01,  3.33531384e-03])

In [143]:
optime

array([-4.41223326e+00, -5.67162220e-02,  3.28335126e+00,  8.52704649e-01,
       -1.03480456e-01, -1.10081558e+00,  5.99993765e-01,  2.69912797e-01,
        3.70845536e-02,  2.62236726e-01,  4.59845153e-01, -8.49686519e-02,
       -3.44278439e-01,  9.92390660e-02,  1.47957563e-01,  1.64034173e-02,
       -6.88797261e-01,  2.16181769e-01,  1.27616455e-01, -1.55815844e-01,
        3.99449197e+00,  2.86412102e-01, -7.50736561e-03, -2.94567031e+00,
        7.67747698e-02,  3.22444373e-01,  3.61534595e-01,  3.33531384e-03])